server:
  port: 18000
logging:
  file:
    name: temp/genhealthApi.log
  level:
    root: info
    org:
      springframework:
        web: debug
spring:
  data:
    mongodb:
      uri: "mongodb+srv://comp3820:mFAR7f6UGzXFZUK0@cluster0.m5swobe.mongodb.net/comp3820?retryWrites=true&w=majority"




FHIRUrl: "https://launch.smarthealthit.org/v/r4/sim/WzQsIiIsIiIsIiIsMCwwLDAsIiIsIiIsIiIsIiIsIiIsIiIsIiIsMCwxXQ/fhir"
DATACOUNT : 3000


