server:
  port: 18000
logging:
  file:
    name: temp/genhealthApi.log
  level:
    root: info
    org:
      springframework:
        web: debug


FHIRUrl: "https://launch.smarthealthit.org/v/r4/sim/WzQsIiIsIiIsIiIsMCwwLDAsIiIsIiIsIiIsIiIsIiIsIiIsIiIsMCwxXQ/fhir"
DATACOUNT : 3000