# 使用Node.js镜像
FROM node:latest as frontend

WORKDIR /app
COPY ./build /app/dist
EXPOSE 3000

# 使用Nginx镜像
FROM nginx:alpine
COPY --from=frontend /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]